version: '3'
services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api_prisma_course
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 3302:3302
      - 5555:5555
